################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

version: "3.6"
volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
services:
  clickevent-generator:
    build: docker/ops-playground-image
    image: apache/flink-ops-playground:1-FLINK-1.16-scala_2.12
    command: "java -classpath /opt/flink/usrlib/ClickCountJob.jar:/opt/flink/lib/* org.apache.flink.playgrounds.ops.clickcount.ClickEventGenerator --bootstrap.servers kafka:9092 --topic input"
    depends_on:
      - kafka
      - zookeeper
  jobmanager-1:
    image: apache/flink-ops-playground:1-FLINK-1.16-scala_2.12
    command: "standalone-job.sh start-foreground --job.classname org.apache.flink.playgrounds.ops.clickcount.ClickEventCount --bootstrap.servers kafka:9092 --event-time --checkpointing"
    depends_on: 
      - kafka
      - zookeeper
    ports:
      - 8081:8081
    volumes:
      - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
      - /tmp/flink/ha:/tmp/flink/ha
  jobmanager-2:
      image: apache/flink-ops-playground:1-FLINK-1.16-scala_2.12
      command: "standalone-job.sh start-foreground --job.classname org.apache.flink.playgrounds.ops.clickcount.ClickEventCount --bootstrap.servers kafka:9092 --event-time --checkpointing"
      depends_on:
        - kafka
        - zookeeper
      ports:
        - 8082:8081
      volumes:
        - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
        - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
        - /tmp/flink/ha:/tmp/flink/ha
  taskmanager:
    image: apache/flink-ops-playground:1-FLINK-1.16-scala_2.12
    depends_on:
      - jobmanager-1
      - jobmanager-2
    command: "taskmanager.sh start-foreground"
    volumes:
      - /tmp/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - /tmp/flink-savepoints-directory:/tmp/flink-savepoints-directory
      - /tmp/flink/ha:/tmp/flink/ha
  zookeeper:
    image: zookeeper:3.8.1
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data:Z
      - zookeeper-log:/var/lib/zookeeper/log:Z
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'false'
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "input:2:1, output:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
      - 9094:9094
  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8080:8080
    links:
      - kafka
#  zoonavigator:
#    container_name: zoonavigator
#    image: elkozmon/zoonavigator:1.1.2
#    ports:
#      - "9000:9000"